stages:
- build
- test
- publish
- cleanup

include:
- local: .gitlab/docker.yml
- local: .gitlab/test.yml

###

.retrieval:
  variables:
    DUP_STAGE: "retrieval"
    IMAGE_NAME: "${CI_REGISTRY}/${CI_PROJECT_NAME}"

.analysis:
  variables:
    DUP_STAGE: "analysis"
    IMAGE_NAME: "${CI_REGISTRY}/${CI_PROJECT_NAME}-analysis"

###

retrieval::build:
  stage: build
  extends: [".retrieval", ".build"]

analysis::build:
  stage: build
  extends: [".analysis", ".build"]


retrieval::test:
  needs: ["retrieval::build"]
  stage: test
  extends: [".retrieval", ".retrieval::test"]

analysis::test:
  needs: ["analysis::build", "retrieval::test"]
  dependencies: ["retrieval::test"]
  stage: test
  extends: [".analysis", ".analysis::test"]


retrieval::publish-image:
  needs: ["retrieval::test"]
  stage: publish
  extends: [".retrieval", ".push"]

analysis::publish-image:
  needs: ["analysis::test"]
  stage: publish
  extends: [".analysis", ".push"]


retrieval::cleanup:
  needs: ["retrieval::publish-image"]
  when: always
  stage: cleanup
  extends: [".retrieval", ".cleanup"]

analysis::cleanup:
  needs: ["analysis::publish-image"]
  when: always
  stage: cleanup
  extends: [".analysis", ".cleanup"]
