stages:
  - test
  - build

test:
  stage: test
  tags: ["docker"]
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_JOB_ID} .
#    - docker run -e FHIR_ENDPOINT="https://mii-agiop-3p.life.uni-leipzig.de/fhir/" ${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_JOB_ID}
  after_script:
    - docker rmi -f ${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_JOB_ID}

.build-image:
  stage: build
  tags: ["docker"]
  script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
    - docker build --pull -t ${image} .
    - docker push ${image}

build-image:latest:
  extends: .build-image
  before_script:
    - image="${CI_REGISTRY}/${CI_PROJECT_NAME}"
  after_script:
    - docker rmi -f "${CI_REGISTRY}/${CI_PROJECT_NAME}"
  only:
    - master

build-image:branch:
  extends: .build-image
  before_script:
    - image="${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
  after_script:
    - docker rmi -f "${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
  only:
    - branches
  except:
    - master

build-image:tag:
  extends: .build-image
  before_script:
    - image="${CI_REGISTRY}/${CI_PROJECT_NAME}:$(echo ${CI_COMMIT_TAG} | cut -c 2-)"
  after_script:
    - docker rmi -f "${CI_REGISTRY}/${CI_PROJECT_NAME}:$(echo ${CI_COMMIT_TAG} | cut -c 2-)"
  only:
    - tags
