stages:
- test
- build

.test:
  stage: test
  tags: ["docker"]
  script:
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
  - docker build -f Dockerfile -t ${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_JOB_ID} .
  - docker run -e MAX_BUNDLES="10" -e FHIR_SERVER_ENDPOINT="${!FHIR_ENDPOINT}" ${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_JOB_ID}
  after_script:
  - docker rmi -f ${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_JOB_ID}
  allow_failure: true # TODO Remove if valid test data available

test-blaze:
  extends: .test
  variables:
    FHIR_ENDPOINT: FHIR_TEST_SERVER_BLAZE

test-hapi:
  extends: .test
  variables:
    FHIR_ENDPOINT: FHIR_TEST_SERVER_HAPI

.build-image:
  stage: build
  tags: ["docker"]
  script:
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
  - "echo \"DUP Version: ${version}\" >> version.txt"
  - docker build -f Dockerfile --pull -t ${image} .
  - docker push ${image}

build-image:latest:
  extends: .build-image
  before_script:
  - image="${CI_REGISTRY}/${CI_PROJECT_NAME}"
  - version="${CI_COMMIT_SHORT_SHA}"
  after_script:
  - docker rmi -f "${CI_REGISTRY}/${CI_PROJECT_NAME}"
  only:
  - master

build-image:branch:
  extends: .build-image
  before_script:
  - image="${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
  - version="${CI_COMMIT_REF_SLUG}"
  after_script:
  - docker rmi -f "${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
  only:
  - branches
  except:
  - master

build-image:tag:
  extends: .build-image
  before_script:
  - image="${CI_REGISTRY}/${CI_PROJECT_NAME}:$(echo ${CI_COMMIT_TAG} | cut -c 2-)"
  - version="${CI_COMMIT_TAG}"
  after_script:
  - docker rmi -f "${CI_REGISTRY}/${CI_PROJECT_NAME}:$(echo ${CI_COMMIT_TAG} | cut -c 2-)"
  only:
  - tags

.build-archive:
  stage: build
  script:
  - "echo \"DUP Version: ${version}\" >> version.txt"
  artifacts:
    paths:
    - "*.Rproj"
    - "*.R"
    - "install-dependencies.*"
    - "version.txt"

build-archive:latest:
  extends: .build-archive
  before_script:
  - version="${CI_COMMIT_SHORT_SHA}"
  artifacts:
    name: "${CI_PROJECT_NAME}-latest"
  only:
  - master

build-archive:branch:
  extends: .build-archive
  before_script:
  - version="${CI_COMMIT_REF_SLUG}"
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}"
  only:
  - branches
  except:
  - master

build-archive:tag:
  extends: .build-archive
  before_script:
  - version="${CI_COMMIT_TAG}"
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
  only:
  - tags
